repos:
  # Ruff for Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        name: Ruff Linter (backend)
        files: ^backend/
        stages: [pre-commit, pre-push]

      - id: ruff-format
        name: Ruff Formatter (backend)
        files: ^backend/
        stages: [pre-commit, pre-push]

  # Check for leaked secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        stages: [pre-commit, pre-push]
