repos:
  # Ruff for Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        name: Ruff Linter (backend - pre-commit)
        files: ^backend/
        args: ["--fix"]
        stages: [pre-commit]

      - id: ruff
        name: Ruff Linter (backend - ci)
        files: ^backend/
        args: ["--no-fix", "--verbose", "--show-fixes", "--show-source"]
        stages: [manual]

      - id: ruff-format
        name: Ruff Formatter (backend - pre-commit)
        files: ^backend/
        stages: [pre-commit]

      - id: ruff-format
        name: Ruff Formatter (backend - ci)
        files: ^backend/
        args: ["--check", "--verbose", "--diff"]
        stages: [manual]

  # Check for leaked secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        stages: [pre-commit, manual]
