# fly.toml app configuration file generated for coach-ai on 2025-05-17T21:58:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coach-ai'
primary_region = 'fra'

[build]
dockerfile = "Dockerfile"


[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']
[http_service.concurrency]
    type = "requests"
    soft_limit = 9

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1

[deploy]
release_command = "uv run alembic upgrade head"
