line-length = 100

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
]
ignore = []

[lint.pydocstyle]
convention = "google"

[format]
line-ending = "lf"
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20