line-length = 100

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "ANN", # flake8-annotations
    "UP",  # pyupgrade
    "N",   # pep8-naming
]
ignore = [
    "UP007", # pyupgrade: suggests Optional[Enum] to be replaced with Enum | None
]

[lint.pydocstyle]
convention = "google"

[format]
line-ending = "lf"
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = 20