name: Bug Report
description: Report a bug in the system.
title: "[Bug] "
labels: ["bug"]
body:
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true


