name: Frontend Backlog
description: Tasks related to UI/UX or frontend logic.
labels: ["frontend"]
projects: "jst-seminar-rostlab-tum/7"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add screenshots or mockups if relevant.
    validations:
      required: false