"""document names in prep and feedback service

Revision ID: 03f53ff9f076
Revises: b2117ff73279
Create Date: 2025-07-07 20:21:24.417580

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03f53ff9f076'
down_revision: Union[str, None] = 'b2117ff73279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenariopreparation', sa.Column('document_names', sa.JSON(), nullable=True))
    op.add_column('sessionfeedback', sa.Column('document_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessionfeedback', 'document_names')
    op.drop_column('scenariopreparation', 'document_names')
    # ### end Alembic commands ###
