"""Remove is_nonprofit

Revision ID: 85e3ba802688
Revises: b4fe22b5dd53
Create Date: 2025-11-12 17:49:07.893399

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '85e3ba802688'
down_revision: Union[str, None] = 'b4fe22b5dd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'is_nonprofit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'userprofile', sa.Column('is_nonprofit', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
