"""on_delete_cascade_live_feedback

Revision ID: 3dfcba1ec486
Revises: 79cce3e613d2
Create Date: 2025-07-10 21:07:10.710458

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3dfcba1ec486'
down_revision: Union[str, None] = '79cce3e613d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAME = 'livefeedback_session_id_fkey'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_NAME, 'livefeedback', type_='foreignkey')
    op.create_foreign_key(
        FK_NAME,
        'livefeedback',
        'session',
        ['session_id'],
        ['id'],
        ondelete='CASCADE',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_NAME, 'livefeedback', type_='foreignkey')
    op.create_foreign_key(
        FK_NAME,
        'livefeedback',
        'session',
        ['session_id'],
        ['id'],
    )
    # ### end Alembic commands ###
