"""Remove doc name add doc metadata

Revision ID: cbc46b1af009
Revises: ab7ebf70f8b9
Create Date: 2025-10-15 01:54:03.699762

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbc46b1af009'
down_revision: Union[str, None] = 'ab7ebf70f8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenariopreparation', sa.Column('documents', sa.JSON(), nullable=True))
    op.drop_column('scenariopreparation', 'document_names')
    op.add_column('sessionfeedback', sa.Column('documents', sa.JSON(), nullable=True))
    op.drop_column('sessionfeedback', 'document_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sessionfeedback',
        sa.Column(
            'document_names',
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column('sessionfeedback', 'documents')
    op.add_column(
        'scenariopreparation',
        sa.Column(
            'document_names',
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column('scenariopreparation', 'documents')
    # ### end Alembic commands ###
