"""change make ai-emotion to optional

Revision ID: 7718ddcf9e37
Revises: d3ba5c881bc7
Create Date: 2025-07-03 18:44:51.770221

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7718ddcf9e37'
down_revision: Union[str, None] = 'd3ba5c881bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessionturn', 'ai_emotion', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessionturn', 'ai_emotion', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
