"""Add user status tracking

Revision ID: b4fe22b5dd53
Revises: f46c560bca8c
Create Date: 2025-11-11 15:31:37.962361

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4fe22b5dd53'
down_revision: Union[str, None] = 'f46c560bca8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('is_nonprofit', sa.Boolean(), nullable=False))
    op.add_column(
        'userprofile',
        sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'organization_name')
    op.drop_column('userprofile', 'is_nonprofit')
    # ### end Alembic commands ###
