"""add persona_name to conversation scenario

Revision ID: 47073b70baec
Revises: fc2c3d9c6394
Create Date: 2025-07-13 15:56:18.761845

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '47073b70baec'
down_revision: Union[str, None] = 'fc2c3d9c6394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conversationscenario',
        sa.Column('persona_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.execute("UPDATE conversationscenario SET persona_name = ''")
    op.alter_column('conversationscenario', 'persona_name', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversationscenario', 'persona_name')
    # ### end Alembic commands ###
