"""Just triggering husky

Revision ID: 8a93adb2c71f
Revises: a93e502a5d3a
Create Date: 2025-07-06 01:08:23.625609

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = '8a93adb2c71f'
down_revision: Union[str, None] = 'a93e502a5d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
