"""Add full_audio_filename and full_audio_start_offset_ms

Revision ID: b2117ff73279
Revises: a93e502a5d3a
Create Date: 2025-07-06 18:04:26.113188

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2117ff73279'
down_revision: Union[str, None] = 'a93e502a5d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'sessionturn', sa.Column('full_audio_start_offset_ms', sa.Integer(), nullable=True)
    )
    op.execute('UPDATE sessionturn SET full_audio_start_offset_ms = 0')
    op.alter_column('sessionturn', 'full_audio_start_offset_ms', nullable=False)

    op.add_column(
        'sessionfeedback',
        sa.Column('full_audio_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.execute("UPDATE sessionfeedback SET full_audio_filename = ''")
    op.alter_column('sessionfeedback', 'full_audio_filename', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessionturn', 'full_audio_start_offset_ms')
    op.drop_column('sessionfeedback', 'full_audio_filename')
    # ### end Alembic commands ###
