"""Added last_loggin_at field to user_profile

Revision ID: a0f89cb0a15d
Revises: a93e502a5d3a
Create Date: 2025-07-05 16:57:34.355970

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0f89cb0a15d'
down_revision: Union[str, None] = 'a93e502a5d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('last_logged_in', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'last_logged_in')
    # ### end Alembic commands ###
