"""merging Alembic heads

Revision ID: d2dab6bb11ac
Revises: 52523a841222
Create Date: 2025-06-29 17:57:24.035359

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = 'd2dab6bb11ac'
down_revision: Union[str, None] = '52523a841222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
