"""Added a new field to the UserProfile Table last_logged_in

Revision ID: ad0abf669301
Revises: 0a10f61dc9c7
Create Date: 2025-06-25 21:32:39.206118

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad0abf669301'
down_revision: Union[str, None] = '0a10f61dc9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('last_logged_in', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'last_logged_in')
    # ### end Alembic commands ###
