"""delete ai_persona in session

Revision ID: 2ec9cbc6c3f2
Revises: 13d3f30289dc
Create Date: 2025-06-30 12:39:02.806824

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ec9cbc6c3f2'
down_revision: Union[str, None] = '13d3f30289dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'ai_persona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'session',
        sa.Column('ai_persona', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###
