"""Add scenario_advice

Revision ID: ab7ebf70f8b9
Revises: 3ef04912413c
Create Date: 2025-07-15 02:19:59.099558

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab7ebf70f8b9'
down_revision: Union[str, None] = '3ef04912413c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('scenario_advice', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'scenario_advice')
    # ### end Alembic commands ###
