"""Added last_logged_in field to User Profile

Revision ID: a1e923719659
Revises: 03f53ff9f076
Create Date: 2025-07-09 16:52:57.436406

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1e923719659'
down_revision: Union[str, None] = '03f53ff9f076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('last_logged_in', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'last_logged_in')
    # ### end Alembic commands ###
