"""move allow_admin_access to session

Revision ID: 54d72c3444d6
Revises: 92a5ad9d1a57
Create Date: 2025-06-25 23:35:06.368858

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54d72c3444d6'
down_revision: Union[str, None] = '92a5ad9d1a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'allow_admin_access')
    op.add_column(
        'session',
        sa.Column(
            'allow_admin_access',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'allow_admin_access')
    op.add_column(
        'review',
        sa.Column(
            'allow_admin_access', sa.Boolean(), nullable=False, server_default=sa.text('false')
        ),
    )
    # ### end Alembic commands ###
