version: "3.8"

services:
  # Supabase-flavoured Postgres (includes pg_graphql, pg_net, pgvector, etc.)
  db:
    image: supabase/postgres:15.8.1.094      # pin! avoid :latest surprises
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54322:5432"                         # exposed only for debugging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Container that executes your Alembic (or similar) migration test script
  test-migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        stage: dev                           # matches multi-stage Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      PGHOST: db
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./backend:/app                       # mount source for flake8/pytest, etc.
      - /app/.venv                           # keep virtual-env cache
      - ./.husky/test-migrations.sh:/test-migrations.sh:ro
    entrypoint: ["/bin/bash", "/test-migrations.sh"]

networks:
  default:
    driver: bridge
