services:
  db:
    image: supabase/postgres:17.0.1.102-orioledb
    restart: unless-stopped
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 60
    networks: [test-network]

  test-migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args: { stage: dev }
    depends_on:
      db: { condition: service_healthy }
    volumes:
      - ./backend:/app
      - /app/.venv
      - ./.husky/test-migrations.sh:/test-migrations.sh
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    entrypoint: ["/bin/bash", "/test-migrations.sh"]
    networks: [test-network]

networks:
  test-network:
