services:
  supabase:
    image: supabase/supabase-dev:latest
    ports:
      - "54321:54321" # API
      - "54322:54322" # DB
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:54321/rest-admin/v1/ready || exit 1" ]
      interval: 3s
      timeout: 3s
      retries: 10

  test-migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args: { stage: dev }
    depends_on:
      supabase:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/.venv
      - ./.husky/test-migrations.sh:/test-migrations.sh
    environment:
      DATABASE_URL: postgresql://postgres:postgres@supabase:54322/postgres
      PGHOST: supabase
      PGPORT: "54322"
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: postgres
    entrypoint: ["/bin/bash", "/test-migrations.sh"]

networks:
  default:
    driver: bridge