name: Check Migrations on PR

on:
  pull_request:

jobs:
  pre-checks:
    name: Pre-migration checks
    runs-on: ubuntu-22.04
    # We must define an output for the next job to use
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for backend changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            backend/app/models/**
            backend/alembic/versions/**
            backend/alembic/data/**
            backend/app/data/**

      # The rest of your pre-check steps are fine, no changes needed here
      - name: Check if dev branch is merged
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          PR_BRANCH: ${{ github.head_ref }}
        run: |
          git fetch origin dev
          git fetch origin $PR_BRANCH
          echo "Checking if origin/dev is merged into $PR_BRANCH"
          if git merge-base --is-ancestor origin/dev origin/$PR_BRANCH; then
            echo "✅ Dev branch is merged"
          else
            echo "❌ Dev branch is not fully merged into this branch"
            echo "Please merge dev branch before proceeding"
            exit 1
          fi

      - name: Check for modified dev migration files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking for modifications to existing migration files from dev..."
          DEV_MIGRATIONS=$(git ls-tree -r --name-only origin/dev -- backend/alembic/versions/ backend/alembic/data/ | grep -E '\.py$|\.sql$' || true)
          if [[ -n "$DEV_MIGRATIONS" ]]; then
            MODIFIED_FILES=""
            for file in $DEV_MIGRATIONS; do
              if git ls-tree -r --name-only HEAD -- "$file" | grep -q .; then
                if ! git diff --quiet origin/dev HEAD -- "$file"; then
                  MODIFIED_FILES="$MODIFIED_FILES\n$file (modified)"
                fi
              else
                MODIFIED_FILES="$MODIFIED_FILES\n$file (deleted)"
              fi
            done
            if [[ -n "$MODIFIED_FILES" ]]; then
              echo "❌ Existing migration files from dev have been altered:"
              echo -e "$MODIFIED_FILES"
              echo "Migration files from dev branch should never be modified or deleted."
              echo "Revert changes and create new migration files instead."
              exit 1
            else
              echo "✅ No existing migration files from dev have been modified"
            fi
          else
            echo "✅ No migration files found on dev branch"
          fi

  migrations:
    name: Check migrations
    runs-on: ubuntu-22.04
    needs: pre-checks # This job depends on the output of pre-checks

    # The job itself is NOT conditional. It will always run.
    # This ensures it always reports a status to GitHub.

    # The Supabase service will only start if there are changes.
    # This saves resources on PRs with no backend changes.
    services:
      supabase:
        if: needs.pre-checks.outputs.any_changed == 'true'
        image: supabase/supabase-dev:latest
        ports:
          - 54321:54321 # API
          - 54322:54322 # DB
        healthcheck:
          test: ["CMD-SHELL", "curl -sf http://localhost:54321/rest/v1/"]
          interval: 5s
          timeout: 5s
          retries: 10

    steps:
      - uses: actions/checkout@v4

      # These steps will ONLY run if backend files were changed.
      - name: Install uv
        if: needs.pre-checks.outputs.any_changed == 'true'
        run: pipx install uv

      - name: Install dependencies
        if: needs.pre-checks.outputs.any_changed == 'true'
        run: uv sync
        working-directory: ./backend

      - name: Run migrations
        if: needs.pre-checks.outputs.any_changed == 'true'
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
        run: |
          echo "✅ Supabase is healthy. Running migration checks..."
          # Assuming your test script uses alembic check or similar
          # You might need to run your test script here, e.g.,
          # bash ./.husky/test-migrations.sh
          cd backend
          alembic check

      # This step will ONLY run if NO backend files were changed.
      # It allows the job to complete successfully.
      - name: No relevant changes, skipping migration checks
        if: needs.pre-checks.outputs.any_changed != 'true'
        run: echo "No relevant changes found. Skipping migration checks."