name: Check Backend on PR

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Install dependencies
        run: uv sync
        working-directory: ./backend
      - name: Run Ruff Linter
        run: uv run pre-commit run --config .pre-commit-config.yaml --hook-stage manual --all-files
        working-directory: ./backend

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Install dependencies
        run: uv sync
        working-directory: ./backend
      - name: Run Tests
        run: uv run pytest --exitfirst --disable-warnings || [[ $? -eq 5 ]]
        working-directory: ./backend

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Install dependencies
        run: uv sync
        working-directory: ./backend
      - name: Build app
        run: uv run python -c "import app.main"
        working-directory: ./backend