name: Check Frontend on PR

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check for frontend changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: frontend/**
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci
        working-directory: ./frontend
      - name: Run ESLint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run lint
        working-directory: ./frontend
      - name: No changes in frontend, skipping lint
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No changes in frontend, skipping lint."

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check for frontend changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: frontend/**
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci
        working-directory: ./frontend
      - name: Run Tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm test
        working-directory: ./frontend
      - name: No changes in frontend, skipping tests
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No changes in frontend, skipping tests."
  
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check for frontend changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: frontend/**
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci
        working-directory: ./frontend
      - name: Build app
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run build
        working-directory: ./frontend
      - name: No changes in frontend, skipping build
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No changes in frontend, skipping build."