name: Check database migrations

on:
  pull_request:
    branches: ["**"]           # run on every PR

jobs:
  pre-checks:
    runs-on: ubuntu-22.04
    outputs:
      backend_changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0       # needed for merge-base checks

      - name: Detect backend-related changes
        id: filter
        uses: tj-actions/changed-files@v46
        with:
          files: |
            backend/app/models/**
            backend/alembic/versions/**
            backend/alembic/data/**
            backend/app/data/**

      - name: Ensure latest dev is merged
        if: steps.filter.outputs.any_changed == 'true'
        run: |
          git fetch origin dev
          if ! git merge-base --is-ancestor origin/dev HEAD; then
            echo "::error::Please merge the latest 'dev' branch into this PR."
            exit 1
          fi
          echo "✅ dev branch is merged."

      - name: Guard against edits to existing migrations
        if: steps.filter.outputs.any_changed == 'true'
        run: |
          set -eo pipefail
          mapfile -t dev_migrations < <(
            git ls-tree -r --name-only origin/dev \
              -- backend/alembic/versions/ backend/alembic/data/ | grep -E '\.(py|sql)$'
          )

          for f in "${dev_migrations[@]}"; do
            git diff --quiet origin/dev -- "$f" && continue
            echo "::error file=$f::Existing migration modified or deleted. Create a new revision instead."
            exit 1
          done
          echo "✅ No existing migrations touched."

      - name: Skip – no backend changes
        if: steps.filter.outputs.any_changed != 'true'
        run: echo "No backend-relevant files changed – skipping migration checks."

  migrations:
    needs: pre-checks
    if: needs.pre-checks.outputs.backend_changed == 'true'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install uv (Python package manager)
        run: pipx install uv

      - name: Sync project dependencies
        run: uv sync
        working-directory: ./backend

      - name: Start minimal Supabase stack
        run: |
          docker compose -f docker-compose.yml \
                         -f docker-compose.ci.yml \
                         up -d --quiet-pull db

          # Wait until Postgres reports ready
          for i in {1..30}; do
            if docker compose exec -T db pg_isready -U postgres -d postgres; then
              echo "✅ Database ready after $((i*2))s"; break
            fi
            sleep 2
          done

      - name: Run migration smoke-test
        run: docker compose -f docker-compose.yml \
                            -f docker-compose.ci.yml \
                            run --build --no-deps test-migrations

      - name: Tear down stack
        if: always()
        run: docker compose -f docker-compose.yml \
                            -f docker-compose.ci.yml down -v
