name: Check Frontend on PR

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run Tests
        run: npm test
        working-directory: ./frontend
  
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build app
        run: npm run build
        working-directory: ./frontend