name: Check Backend on PR

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync
        working-directory: ./backend

      - name: Run Ruff Linter
        run: uv run pre-commit run --config .pre-commit-config.yaml --hook-stage manual --all-files
        working-directory: ./backend

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync
        working-directory: ./backend

      - name: Run Tests
        run: uv run pytest --exitfirst --disable-warnings || [[ $? -eq 5 ]]
        working-directory: ./backend