name: Check Migrations on PR

on:
  pull_request:

jobs:
  pre-checks:
    name: Pre-migration checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for backend changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            backend/app/models/**
            backend/alembic/versions/**
            backend/alembic/data/**
            backend/app/data/**

      - name: Check if dev branch is merged
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          MERGE_BASE=$(git merge-base HEAD origin/dev)   
          DEV_HEAD=$(git rev-parse origin/dev)  

          if [[ "$MERGE_BASE" == "$DEV_HEAD" ]]; then
            echo "✅ Dev branch is merged"
          else
            echo "❌ Dev branch is not fully merged into this branch"
            echo "Please merge dev branch before proceeding"
            exit 1
          fi

      - name: Check for modified dev migration files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking for modifications to existing migration files from dev..."

          # Get list of migration files that exist on dev branch
          DEV_MIGRATIONS=$(git ls-tree -r --name-only origin/dev -- backend/alembic/versions/ backend/alembic/data/ | grep -E '\.py$|\.sql$' || true)

          if [[ -n "$DEV_MIGRATIONS" ]]; then
            echo "Migration files found on dev branch:"
            echo "$DEV_MIGRATIONS"

            MODIFIED_FILES=""
            for file in $DEV_MIGRATIONS; do
              # Does the file exist in this PR branch?
              if git ls-tree -r --name-only HEAD -- "$file" | grep -q .; then
                # File exists; check if modified
                if ! git diff --quiet origin/dev HEAD -- "$file"; then
                  MODIFIED_FILES="$MODIFIED_FILES\n$file (modified)"
                fi
              else
                # File is missing in PR branch (i.e. deleted)
                MODIFIED_FILES="$MODIFIED_FILES\n$file (deleted)"
              fi
            done

            if [[ -n "$MODIFIED_FILES" ]]; then
              echo "❌ Existing migration files from dev have been altered:"
              echo -e "$MODIFIED_FILES"
              echo ""
              echo "Migration files from dev branch should never be modified or deleted."
              echo "Revert changes and create new migration files instead."
              exit 1
            else
              echo "✅ No existing migration files from dev have been modified"
            fi
          else
            echo "✅ No migration files found on dev branch"
          fi

      - name: No relevant changes, skipping migration pre-checks
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No relevant changes, skipping migration pre-checks."

  migrations:
    name: Check migrations
    runs-on: ubuntu-22.04
    needs: pre-checks
    steps:
      - uses: actions/checkout@v4

      - name: Check for backend changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            backend/app/models/**
            backend/alembic/versions/**
            backend/alembic/data/**
            backend/app/data/**

      - name: Install uv
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pipx install uv

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: uv sync
        working-directory: ./backend

      - name: Create network
        if: steps.changed-files.outputs.any_changed == 'true'
        run: docker network create app-network

      - name: Start Supabase
        if: steps.changed-files.outputs.any_changed == 'true'
        run: docker compose -f docker-compose.yml -f .husky/docker-compose.ci.yml up -d --remove-orphans supabase
      - name: Check if port 54321 is open
        run: |
          echo "Checking if Supabase port is open..."
          ss -ltnp | grep 54321 || echo "Port 54321 not found"

      - name: Wait for Supabase to become healthy
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Waiting for Supabase to be healthy..."
          for i in {1..60}; do
            health=$(curl -sf http://127.0.0.1:54321/rest-admin/v1/ready || echo "unhealthy")
            if [[ "$health" != "unhealthy" ]]; then
              echo "✅ Supabase is ready"
              break
            fi
            echo "⏳ Supabase not ready yet... ($((i*2))s)"
            sleep 2
            if [[ $i -eq 60 ]]; then
              echo "❌ Supabase not healthy after 2 minutes"
              docker ps -a
              docker compose -f docker-compose.yml -f .husky/docker-compose.ci.yml logs supabase
              exit 1
            fi
          done

      - name: Run test-migrations container
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          CID=$(docker compose -f docker-compose.yml -f .husky/docker-compose.ci.yml run --build --no-deps -d test-migrations)
          docker logs -f "$CID"
          EXIT=$(docker wait "$CID")
          if [[ "$EXIT" -eq 0 ]]; then
            echo "✅- Migration checks passed"
          else
            echo "❌- Migration checks failed"
            exit 1
          fi

      - name: No relevant changes, skipping migration checks
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No relevant changes, skipping migration checks."
