name: Deploy Backend to Fly.io

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]


jobs:
#  Add test and linting when ready
  deploy-production:
    name: Deploy (Production)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy with Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
