name: Deploy Dev Backend to Fly.io

on:
  push:
    branches: [ dev ]
    paths: [ 'backend/**' ]


jobs:
#  Add test and linting when ready
  deploy-production:
    name: Deploy Dev Server (Production mode)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Dev with Fly.io
        run: flyctl deploy --config fly.dev.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV }}
