name: Deploy Frontend to Vercel

#on:
#  push:
#    branches: [ main ]
#    paths: [ 'frontend/**' ]   # Only run when frontend files change

on:
  push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run Tests
        run: npm test
        working-directory: ./frontend

  build:
    name: Build
    needs: [ lint ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build app
        run: npm run build
        working-directory: ./frontend

#  deploy-production:
#    name: Deploy (Production)
#    needs: [ lint, build ]
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v4

#      - name: Install Vercel CLI
#        run: npm install --global vercel@latest
#
#      - name: Pull Vercel Environment Information
#        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
#        working-directory: ./frontend

#      - name: Build Project Artifacts
#        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
#        working-directory: ./frontend

#      - name: Deploy Project Artifacts to Vercel
#        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
#        working-directory: ./frontend
