name: Deploy Frontend to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [ ci/add-alembic ]
    paths: [ 'frontend/**' ]   # Only run when frontend files change

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run Tests
        run: npm test
        working-directory: ./frontend

  build:
    name: Build
    needs: [ test ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build app
        run: npm run build
        working-directory: ./frontend

  #deploy:
  #  name: Deploy (Production)
  #  needs: [ build ]
  #  runs-on: ubuntu-22.04
  #  steps:
  #    - uses: actions/checkout@v4

  #    - name: Install Vercel CLI
  #      run: npm install --global vercel@latest

  #    - name: Pull Vercel Environment Information
  #      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
  #      working-directory: ./frontend

  #    - name: Build Project Artifacts
  #      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
  #      working-directory: ./frontend

  #    - name: Deploy Project Artifacts to Vercel
  #      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  #      working-directory: ./frontend
